
['In']
m_Colour = 0x0F0F0F
m_Label = "In"

	[['In'.m_Outputs]]
	m_Type = 'Emitter'
	m_Label = ""

['Out']
m_Colour = 0x0F0F0F
m_Label = "Out"

	[['Out'.m_Inputs]]
	m_Type = 'Emitter'
	m_Label = ""

['Fast']
m_Colour = 0x11DD11
m_Label = "Fast"

	[['Fast'.m_Outputs]]
	m_Type = 'float'
	m_Label = ""

['Slow']
m_Colour = 0x11DD11
m_Label = "Slow"

	[['Slow'.m_Outputs]]
	m_Type = 'float'
	m_Label = ""

['Small']
m_Colour = 0x1111DD
m_Label = "Small"

	[['Small'.m_Outputs]]
	m_Type = 'float'
	m_Label = ""

['Medium']
m_Colour = 0x1111DD
m_Label = "Medium"

	[['Medium'.m_Outputs]]
	m_Type = 'float'
	m_Label = ""

['Large']
m_Colour = 0x1111DD
m_Label = "Large"

	[['Large'.m_Outputs]]
	m_Type = 'float'
	m_Label = ""

['emitter::Explosion']
m_Colour = 0xDD1111
m_Label = "Explosion"
m_Tooltip = "Creates an explosion that will trigger 'OnHit' on all entities it contacts."

	[['emitter::Explosion'.m_Inputs]]
	m_Type = 'Emitter'
	m_Label = ""

	[['emitter::Explosion'.m_Inputs]]
	m_Type = 'float'
	m_Label = "Radius"

	[['emitter::Explosion'.m_Outputs]]
	m_Type = 'Emitter'
	m_Label = ""

['emitter::Projectile']
m_Colour = 0xDD1111
m_Label = "Projectile"
m_Tooltip = "Creates a projectile that will trigger 'OnHit' to the first entity it contacts."

	[['emitter::Projectile'.m_Inputs]]
	m_Type = 'Emitter'
	m_Label = ""

	[['emitter::Projectile'.m_Inputs]]
	m_Type = 'float'
	m_Label = "Speed"

	[['emitter::Projectile'.m_Outputs]]
	m_Type = 'Emitter'
	m_Label = ""
